<?php

namespace Laravel\Tinker\Shell;

use Psy\Shell;

class CustomShell extends Shell
{
    protected function getDefaultLoopListeners(): array
    {
        $listeners = parent::getDefaultLoopListeners(); // TODO: Change the autogenerated stub

        $listeners[] = new ShellLogListener();

        return $listeners;
    }
}
